# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/data.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='proto/data.proto',
  package='proto',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x10proto/data.proto\x12\x05proto\"A\n\x0bInputRecord\x12\x0f\n\x02id\x18\x01 \x01(\tH\x00\x88\x01\x01\x12\x11\n\x04text\x18\x02 \x01(\tH\x01\x88\x01\x01\x42\x05\n\x03_idB\x07\n\x05_text\",\n\x05Input\x12#\n\x07records\x18\x01 \x03(\x0b\x32\x12.proto.InputRecord\"|\n\x0cOutputRecord\x12\x0f\n\x02id\x18\x01 \x01(\tH\x00\x88\x01\x01\x12\x17\n\nclassifier\x18\x02 \x01(\x05H\x01\x88\x01\x01\x12\x1a\n\rrawclassifier\x18\x03 \x01(\x05H\x02\x88\x01\x01\x42\x05\n\x03_idB\r\n\x0b_classifierB\x10\n\x0e_rawclassifier\".\n\x06Output\x12$\n\x07records\x18\x01 \x03(\x0b\x32\x13.proto.OutputRecord23\n\x0c\x43lassifyData\x12#\n\x02\x44o\x12\x0c.proto.Input\x1a\r.proto.Output\"\x00\x62\x06proto3'
)




_INPUTRECORD = _descriptor.Descriptor(
  name='InputRecord',
  full_name='proto.InputRecord',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='proto.InputRecord.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='text', full_name='proto.InputRecord.text', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='_id', full_name='proto.InputRecord._id',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_text', full_name='proto.InputRecord._text',
      index=1, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=27,
  serialized_end=92,
)


_INPUT = _descriptor.Descriptor(
  name='Input',
  full_name='proto.Input',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='records', full_name='proto.Input.records', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=94,
  serialized_end=138,
)


_OUTPUTRECORD = _descriptor.Descriptor(
  name='OutputRecord',
  full_name='proto.OutputRecord',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='proto.OutputRecord.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='classifier', full_name='proto.OutputRecord.classifier', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='rawclassifier', full_name='proto.OutputRecord.rawclassifier', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='_id', full_name='proto.OutputRecord._id',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_classifier', full_name='proto.OutputRecord._classifier',
      index=1, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
    _descriptor.OneofDescriptor(
      name='_rawclassifier', full_name='proto.OutputRecord._rawclassifier',
      index=2, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=140,
  serialized_end=264,
)


_OUTPUT = _descriptor.Descriptor(
  name='Output',
  full_name='proto.Output',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='records', full_name='proto.Output.records', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=266,
  serialized_end=312,
)

_INPUTRECORD.oneofs_by_name['_id'].fields.append(
  _INPUTRECORD.fields_by_name['id'])
_INPUTRECORD.fields_by_name['id'].containing_oneof = _INPUTRECORD.oneofs_by_name['_id']
_INPUTRECORD.oneofs_by_name['_text'].fields.append(
  _INPUTRECORD.fields_by_name['text'])
_INPUTRECORD.fields_by_name['text'].containing_oneof = _INPUTRECORD.oneofs_by_name['_text']
_INPUT.fields_by_name['records'].message_type = _INPUTRECORD
_OUTPUTRECORD.oneofs_by_name['_id'].fields.append(
  _OUTPUTRECORD.fields_by_name['id'])
_OUTPUTRECORD.fields_by_name['id'].containing_oneof = _OUTPUTRECORD.oneofs_by_name['_id']
_OUTPUTRECORD.oneofs_by_name['_classifier'].fields.append(
  _OUTPUTRECORD.fields_by_name['classifier'])
_OUTPUTRECORD.fields_by_name['classifier'].containing_oneof = _OUTPUTRECORD.oneofs_by_name['_classifier']
_OUTPUTRECORD.oneofs_by_name['_rawclassifier'].fields.append(
  _OUTPUTRECORD.fields_by_name['rawclassifier'])
_OUTPUTRECORD.fields_by_name['rawclassifier'].containing_oneof = _OUTPUTRECORD.oneofs_by_name['_rawclassifier']
_OUTPUT.fields_by_name['records'].message_type = _OUTPUTRECORD
DESCRIPTOR.message_types_by_name['InputRecord'] = _INPUTRECORD
DESCRIPTOR.message_types_by_name['Input'] = _INPUT
DESCRIPTOR.message_types_by_name['OutputRecord'] = _OUTPUTRECORD
DESCRIPTOR.message_types_by_name['Output'] = _OUTPUT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

InputRecord = _reflection.GeneratedProtocolMessageType('InputRecord', (_message.Message,), {
  'DESCRIPTOR' : _INPUTRECORD,
  '__module__' : 'proto.data_pb2'
  # @@protoc_insertion_point(class_scope:proto.InputRecord)
  })
_sym_db.RegisterMessage(InputRecord)

Input = _reflection.GeneratedProtocolMessageType('Input', (_message.Message,), {
  'DESCRIPTOR' : _INPUT,
  '__module__' : 'proto.data_pb2'
  # @@protoc_insertion_point(class_scope:proto.Input)
  })
_sym_db.RegisterMessage(Input)

OutputRecord = _reflection.GeneratedProtocolMessageType('OutputRecord', (_message.Message,), {
  'DESCRIPTOR' : _OUTPUTRECORD,
  '__module__' : 'proto.data_pb2'
  # @@protoc_insertion_point(class_scope:proto.OutputRecord)
  })
_sym_db.RegisterMessage(OutputRecord)

Output = _reflection.GeneratedProtocolMessageType('Output', (_message.Message,), {
  'DESCRIPTOR' : _OUTPUT,
  '__module__' : 'proto.data_pb2'
  # @@protoc_insertion_point(class_scope:proto.Output)
  })
_sym_db.RegisterMessage(Output)



_CLASSIFYDATA = _descriptor.ServiceDescriptor(
  name='ClassifyData',
  full_name='proto.ClassifyData',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=314,
  serialized_end=365,
  methods=[
  _descriptor.MethodDescriptor(
    name='Do',
    full_name='proto.ClassifyData.Do',
    index=0,
    containing_service=None,
    input_type=_INPUT,
    output_type=_OUTPUT,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_CLASSIFYDATA)

DESCRIPTOR.services_by_name['ClassifyData'] = _CLASSIFYDATA

# @@protoc_insertion_point(module_scope)
